### ISSUE TITLE
구독자입니다 질문사항 올립니다 (part6 회원가입 http ConnectionError)

### ISSUE THREAD

**Issue by moorekwon** [rampart81/python-backend-book#5]
책을 구독하면서 공부하는 와중에, 해결이 안되는 에러가 계속 떠서 issue 올립니다.
new connection에 실패했다고 뜨는데, 왜그런건가요?
github에 올려진 코드 그대로 작성했습니다.

![image](https://user-images.githubusercontent.com/45852742/84122056-d2ed9280-aa72-11ea-82c7-7c9e08342029.png)

**Comment by rampart81** [comment]
안녕하세요! 답이 너무 늦었습니다.

보내주신 에러 메세지에 의하면 서버가 돌아가고 있지 않아서 생기는 에러로 보입니다.
다음 중 하나를 확인 하시면 될것 같습니다:

- 서버가 제대로 시작이 되었는지?
- 서버가 5000번 포트에서 시작 되었는지?
